---
title: "Cvičení 8: Jednotkové testovanie"
layout: "seminar"
author: "Roman Lacko"
author-email: "xlacko1@fi.muni.cz"
publish: now
---

= Cvičení 8: Jednotkové testovanie

Na minulom cvičení ste si skúsili implementovať jednoduchú dátovú štruktúru,
__spájaný zoznam__. Na dnešom cvičení sa úlohy obrátia. V kostre máte
pripravenú implementáciu úplne inej dátovej štruktúry a vašou úlohou
je pomocou testov odhaliť niekoľko chýb voči dokumentácii.

== Epizóda 2: Attack of the Bugs

'''

=== Zadanie

V hlavičke `queue.h` sa nachádza deklarácia dátovej štruktúry
__cyklický rad s fixnou veľkosťou__ (angl. __fixed-size cyclic queue__).
Vašou úlohou je do `tests.c` napísať testy pre každú funkciu tak, aby ste
odhalili chyby implementácie voči očakávanému chovaniu popísanému
v dokumentácii hlavičkového súboru.

=== Popis cyklického radu

Rad (čes. __fronta__, angl. __queue__) je abstraktná dátová štruktúra,
ktorá má typicky dve operácie, `enqueue` a `dequeue` (môžu sa volať aj inak).
Prvá operácia prvky do radu vkladá, druhá ich vyberá.
Prvky sa z radu vyberajú presne v takom poradí, v akom sa vkladajú.

V kontexte minulého cvičenia by bolo možné rad implementovať pomocou
obojsmerne spájaného zoznamu napríklad tak, že

* `enqueue` urobí `listPush`,
* `dequeue` urobí `listShift`,
* ostatné operácie `listPop` a `listUnshift` sa zakážu

Variant, kedy sa použije `listUnshift` a `listPop` bude fungovať tiež.

Implementácia použitá v tomto cvičení však spájaný zoznam nepoužíva,
pretože by ste museli testovať aj interné stavy uzlov. Implementácia
preto používa pevnú veľkosť (__fixed size__), pričom sa recykluje
stále rovnaký úsek pamäte akoby "do kruhu" (__cyclic__).

Štruktúra `struct queue` obsahuje 5 položiek:

* `size_t element` -- veľkosť prvkov
* `size_t capacity` -- počet prvkov, ktoré sa dajú uložiť v rade
* `size_t index` -- index prvku v pomyslenom poli radu, ktorý sa najbližšie
  vyberie operáciou `dequeue`, ak sú v rade nejaké prvky
* `size_t size` -- počet aktuálne uložených prvkov
* `void *memory` -- interná pamäť radu

Pri vložení prvku do radu sa hodnota (**nie pointer**) skopíruje do
poľa `memory` na pozíciu tak, aby bol `size * element` bytov ďaleko od
`index`. Ak by táto hodnota prekročila veľkosť pamäte, tak sa začne znova od
začiatku. Prvky sa vyberajú jednoducho z pozície označenej ako `index`,
jeho hodnota s následne zvýši alebo vráti na 0, ak by sa dostala na `capacity`.

**Príklad**

Majme rad znakov (`char`) kapacity 4, ktorý je iniciálne prázdny.
To znamená, že `element = sizeof(char)`, `capacity = 4`, `index = 0`
a `size = 0`. Rad zapíšeme ako `[>?,?,?,?]`, kde `>` označuje index.
Hodnoty `?` sú neinicializované alebo neznáme.

* vložením znakov `a`, `b` a `c` vznikne rad `[>a,b,c,?]`
* výberom znaku dostaneme `a`, ostane rad `[?,>b,c,?]`
* výberom ďalšieho znaku dostaneme `b`, ostane rad `[?,?,>c,?]`
* vložením znaku `d` dostaneme rad `[?,?,>c,d]`
* vložením ďalšieho znaku `e` sa prvky začnú vkladať odzačiatku, tj.
  dostaneme rad `[e,?,>c,d]`

=== Popis operácií

[.alert.alert-info]
icon:info[role="mr-2"] Primárne používajte dokumentáciu v hlavičkovom súbore.

[source,c]
----
bool queueCreate(struct queue **queue, size_t elementSize, size_t capacity);
----

* **alokuje** pamäť pre štruktúru a pointer uloží do `&queue`
* **alokuje** pamäť pre `memory` tak, aby bola schopná uložiť
  `capacity` prvkov veľkosti `elementSize`
* ak sa niektorá alokácia nepodarí, dealokuje všetku doteraz alokovanú pamäť
  a zlyhá (vráti `false`) bez toho, aby zmenila pointer v prvom parametri
* po úspešnej alokácii nastaví správne hodnoty do štruktúry a vráti `true`

[source,c]
----
void queueDestroy(struct queue *queue);
----

* dealokuje štruktúru alokovanú pomocou `queueCreate`; pre ostatné objekty
  nemá definované chovanie

[source,c]
----
size_t queueElementSize(const struct queue *queue);
size_t queueCapacity(const struct queue *queue);
size_t queueSize(const struct queue *queue);
----

* informácie o rade

[source,c]
----
bool queueIsEmpty(const struct queue *queue);
bool queueIsFull(const struct queue *queue);
----

* test prázdnosti resp. plnosti
* rad chápeme plný vtedy, ak veľkosť dosiahla jeho kapacitu

[source,c]
----
bool queueEnqueue(struct queue *queue, const void *data);
----

* implementuje operáciu `enqueue`
* ak je v rade miesto, __skopíruje__ `queue\->element` bytov z ukazateľa
  `data` do svojej internej pamäte a vráti `true`
* ak je rad plný, vráti `false`

[source,c]
----
bool queueDequeue(struct queue *queue, void *data);
----

* implementuje operáciu `dequeue`
* ak je v rade aspoň jeden prvok, skopíruje `queue\->element` bytov
  z internej pamäte tam, kam ukazuje `data`, posunie index a vráti `true`
* ak je `data` `NULL`, tak len posunie index a vráti `true`
  (dá sa chápať ako zmazanie prvku)
* ak je rad prázdny, vráti `false` bez zmeny pamäte, kam ukazuje `data`

[source,c]
----
const void *queuePeek(const struct queue *queue);
----

* vráti konštantný ukazateľ do internej pamäte na prvok, ktorý
  by sa vybral operáciou `queueDequeue`
* štruktúra ani obsah internej pamäte sa nijak nezmení
* ak je rad prázdny, vráti `NULL`

Ukážku použitia tejto štruktúry nájdete v `playground.c`.

=== Prečo zdrojový kód vyzerá ako Perl?

Cieľom cvičenia je testovať chovanie štruktúry podľa dokumentácie.
Často je možné odhaliť chyby jednoduchým prečítaním zdrojového kódu, obzvlášť
v  implementáciách, ako je táto. Aby sme tomu zabránili,
zdrojový kód dodaný k cvičeniu prešiel procesom __obfuskácie__.

Obfuskácia sa používa vtedy, ak chceme čo najviac sťažiť porozumenie
zdrojového kódu. Existuje niekoľko rôznych metód, zdrojový kód v kostre
cvičenia prešiel ručným nahradzovaním kusov kódu za nezmyselne pomenované
makrá.

'''

== Úloha: Testovanie

Cvičiaci vytvorí v službe link:http://collabedit.com/[collabedit]
zdieľaný dokument, do ktorého sa budú ukladať testy.
Následne rozdelí študentov do niekoľkých skupín, pričom každá skupina dostane
pár funkcí na otestovanie. Odporúčané rozdelenie je na 4 skupiny:

. `queueSize`, `queueElementSize`, `queueCapacity`
. `queuePeek`, `queueIsFull`, `queueIsEmpty`
. `queueCreate`, `queueEnqueue`
. `queueDequeue`

Študenti v skupine môžu diskutovať o prípadoch, ktoré by mali otestovať,
a následne k nim písať testy. Svoje testy študenti priebežne kopírujú
do zdieľaného dokumentu. Cvičiaci tieto testy občas spustí a prípadne vysvetlí,
prečo zlyhali. Cieľom je pomocou testov nájsť chyby voči dokumentácii.

=== Testovací framework

Testy píšte do `tests.c`. Tento súbor nemá funkciu `main`,
obsahuje len testy. Každý test sa začína makrom `TEST` s názvom testu.

V tele v blokových zátvorkých je možné písať ľubovoľný kód jazyka C,
môžete volať funkcie, deklarovať premenné, používať cykly atď. Okrem toho
môžete používať makro `ASSERT`, ktoré skontroluje, že nejaká podmienka platí,
inak test skončí neúspešne.

[source,c]
----
TEST(zero)
{
    int zero = 0;
    ASSERT(zero == 0);
}
----

=== Ako na jednotkové testovanie

Testovanie je všeobecne veľmi ťažké a trvá dlhý čas, kým sa programátor
naučí poriadne testovať. Táto časť preto uvádza len veľmi jednoduché rady,
čo pri testovaní robiť a čo nie.

==== Testujte vždy len jednu funkciu

Predstavte si takýto test:

[source,c]
----
TEST(velky_spatny)
{
    struct queue *queue;
    queueCreate(&queue, sizeof(int), 16u);

    int data = 42;
    queueEnqueue(queue, &data);
    ASSERT(queueSize(queue) == 1u);
}
----

Ak tento test zlyhá, nedá sa jednoznačne povedať, ktorá funkcia za to môže.
Chyba môže byť v `queueSize`, `queueEnqueue` alebo rovnako aj `queueCreate`.

Každý `TEST` by mal preto volať len jednu funkciu z testovaného rozhrania.

==== Vytvárajte štruktúru sami

Keďže by ste vďaka predchádzajúcemu bodu nemali volať `queueInitialize`
s výnimkou testu priamo pre túto funkciu, musíte si štruktúru vyrobiť sami
pred každým testom. Takto máte kontrolu nad vstupom funkcie
a môžete jednoducho otestovať, že po skončení sa štruktúra zmenila očakávaným
spôsobom.

Príklady nájdete v ukážkových testoch v `tests.c`.

==== Každý test nech testuje jeden prípad

Aby bolo možné ľahko odlíšiť okolnosti, za akých sa funkcia nespráva očakávane,
každý test by mal testovať jeden špecifický scenár.

Napríklad, pre test `queueEnqueue` môžeme testovať tieto prípady:

* prázdny rad s nenulovou kapacitou
* čiastočne zaplnený rad, v ktorom je miesto na konci
* čiastočne zaplnený rad, v ktorom je miesto na začiatku
* plný rad
* ...

Pre každý takýto prípad by mal exitovať samostatný test.
Tieto testy môžete pomenovať `+++nazovTestovanejFunkcie__pripad+++`,
napríklad `+++queueEnqueue__empty_with_nonzero_capacity+++`.

==== Nepoužívajte náhodnosť

Testy založené na náhodnosti sú veľmi užitočné, ale je ťažké ich
urobiť správne. Jeden z hlavných problémov je determinizácia.
V prípade, že test zlyhá, je často nutné takýto test zopakovať, napríklad
kvôli ladeniu. Na toto cvičenie náhodné testy nepotrebujete.
